import { Address } from 'viem';

/**
 * Buy Coin Transaction Type
 * Used for creating DAO proposals to purchase Zora creator coins
 */
export interface BuyCoinTransaction {
  // User-provided fields
  coinAddress: Address;
  coinName?: string; // Display name (optional)
  ethAmount: string; // ETH amount as string (e.g., "0.1")
  slippage: string; // Slippage tolerance as percentage string (e.g., "5")

  // SDK-generated fields (populated when generating transaction)
  target?: Address; // Router contract address
  calldata?: `0x${string}`; // Encoded swap calldata
  value?: string; // ETH value to send
}

/**
 * Parameters for generating a buy coin transaction via SDK
 */
export interface GenerateBuyCoinParams {
  coinAddress: Address;
  ethAmount: string;
  slippage: string;
  treasuryAddress: Address;
}

/**
 * Trade data generated by Zora Coins SDK
 */
export interface GeneratedTradeData {
  target: Address; // Router contract
  calldata: `0x${string}`; // Encoded swap call
  value: string; // ETH value (formatted)
}

/**
 * Proposal transaction structure for Governor contract
 */
export interface ProposalTransaction {
  target: `0x${string}`;
  value: bigint;
  calldata: `0x${string}`;
}
